// Svelte/fileServer/src/routes/login/+page.svelte
<script>
    import axios from "axios";


    let loginForm = {
        memberName: '',
        memberPw: '',
    };
    let isLoading = false;

    const loginProc = () => {
        if (loginForm.memberName === '') {
            return false;
        }
        if (loginForm.memberPw === '') {
            return false;
        }

        const formData = new FormData();

        formData.append("memberName", loginForm.memberName)
        formData.append("memberPw", loginForm.memberPw)

        axios.post('/api/login/login', formData)
            .then((res) => {
                const data = res.data.data.view;
                if (res.data.success) {
                    localStorage.setItem('userToken', data.userToken);

                    window.location.href = '/'
                }
            })
            .catch((err) => {
                console.log('login error :>>>> ', err);
            })
            .finally(() => {
                isLoading = false;
            })
    }

</script>

<div>
    <div class="loginDiv">
        <form class="loginForm">
            <input
                    id="input-1"
                    placeholder="Enter name"
                    required
                    bind:value="{loginForm.memberName}"
            >
            <input
                    id="input-2"
                    placeholder="Enter password"
                    type="password"
                    required
                    bind:value="{loginForm.memberPw}"
            >
            <button
                    on:click="{loginProc}"
                    style="width: 100%; background-color: #ff9c00"
            >
                <span>로그인</span>
                <!--                <spinner small v-if="isLoading"></spinner>-->
            </button>
        </form>
    </div>
</div>

// node/pages/Login.vue
<template>
  <div>
    <div class="loginDiv">
      <b-form class="loginForm">
        <b-form-group id="input-group-1" label="아이디" label-for="input-1">
          <b-form-input
            id="input-1"
            placeholder="Enter name"
            required
            v-model="loginForm.memberName"
          ></b-form-input>
        </b-form-group>

        <b-form-group id="input-group-2" label="비밀번호" label-for="input-2">
          <b-form-input
            id="input-2"
            placeholder="Enter password"
            type="password"
            required
            v-model="loginForm.memberPw"
          ></b-form-input>
        </b-form-group>

        <b-button
          @click="login"
          variant="primary"
          style="width: 100%; background-color: #ff9c00"
        >
          <span>로그인</span>
          <b-spinner small v-if="isLoading"></b-spinner>
        </b-button>
      </b-form>
    </div>
  </div>
</template>

<script>
export default {
  name: "Login",
  layout: 'NoHeader',
  components: {

  },

  data() {
    return {
      loginForm: {
        memberName: '',
        memberPw: '',
      },
      isLoading: false,
    }
  },

  methods: {
    login() {
      this.isLoading = true;

      const formData = new FormData();
      formData.append("memberName", this.loginForm.memberName)
      formData.append("memberPw", this.loginForm.memberPw)

      this.$axios.post('/api/login/login', formData)
        .then((res) => {
          const data = res.data.data.view;
          if(res.data.success) {
            localStorage.setItem('userToken', data.userToken);

            this.$router.push('/')
          }
        })
        .catch((err) => {
          console.log('login error :>>>> ', err);
        })
        .finally(() => {
          this.isLoading = false;
        })
    },
  },

}
</script>

<style scoped>
  .loginDiv {
    text-align: -webkit-center;
  }
  .loginForm {
    width: 400px;
    text-align: left;
  }
</style>
